name: Crear un wokflow que simule los siguientes estados de CI/CD buid , test y push
on:
  push

jobs:
  buildeo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "La app se ha buildeado correctamente!"

  testeo:
    runs-on: ubuntu-latest
    needs: buildeo
    if: ${{ success() }}
    steps:
      - run: echo "Los test han corrido exitosamente!"

  pusheo:
    runs-on: ubuntu-latest
    needs: testeo
    if: ${{ success() }}
    steps:
      - run: echo "Build pusheada correctamente!"