name: Generar una issue al abrir un pull request. Y más
on:
  pull_request:
    types: 
      - opened
      - reopened

jobs:
  buildeo:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - run: |
          "issue_id=$(gh issue create --assignee davidnboffelli --title 'Issue test' --body 'Issue generada en un job'") >> $GITHUB_OUTPUT
        id: create_issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          "gh pr edit ${{ github.event.number }} --body '#${{ steps.create_issue.outputs.issue_id }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}