name: Conseguir hacer login en azure con vuestras cuentas (con bash y con actions del marketplace)
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  
jobs:
  login-azure:
    runs-on: ubuntu-latest
    steps:
      - run: |
          az login \
          --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password "${ secrets.SERVICE_PRINCIPAL_SECRET }" \
          --tenant ${{ secrets.AZURE_TENANT_ID }}