name: Generar una issue al abrir un pull request. Y más
on:
  pull_request:
    types: 
      - opened
      - reopened

jobs:
  buildeo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - run: |
          gh issue create -a @me --title "Issue test" --body "Issue generada en un job"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}