name: Crear una calculadora. Mediante inputs donde nos permita indicar la operación y sus valores de entrada
on:
  workflow_dispatch:
    inputs:
      operacion:
        description: '+,-,*,/'
        required: true
        type: choice
        options:
            - sumar
            - restar
            - multiplicar
            - dividir
      valor1:
        description: 'primer operando'
        required: true
      valor2:
        description: 'segundo operando'
        required: true

jobs:
  calculadora:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "${{ github.event.inputs.operacion }}" = "sumar" ]; then
          resultado=$((github.event.inputs.valor1 + github.event.inputs.valor2))
          fi
