name: Publish to Docker
on:
  workflow_call:
    inputs:
      image-to-build:
        required: true
        type: string
      reg.io:
        required: true
        type: string
permissions:
  packages: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "pepe"
