name: My Starter Workflow

on:
  workflow_dispatch:
permissions: write-all 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
          
  call-reusable-workflow:
    permissions: write-all 
    uses: ./.github/workflows/ejercicio6-reutilizable.yml
    with:
      image-to-build: ghcr.io/stemdo-labs/publish-packages-davidnboffelli/game
      regio: ghcr.io
