name: Ejecutar un script al hacer push, mostrando información del runner y la rama.
on:
  push

jobs:
  show-information:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Runner's OS: ${{ runner.os }}"
          echo "Branch: ${{ github.ref_name }}"