name: Reusable Workflow

on:
  workflow_call:
    inputs:
      image-to-build:
        required: true
        type: string
      regio:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Output the input value
        run: |
          echo "The node version to use is: ${{ inputs.image-to-build }}"
          echo "and ${{ inputs.regio }}"

      - name: Checkout
        uses: actions/checkout@v4
      # Add your test steps here if needed...
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ image-to-build }}
          tags: type=sha
