name: Ejecutar un script al hacer push, mostrando información del runner y la rama.
on:
  push

jobs:
  buildeo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "La app se ha buildeado correctamente!"

  testeo:
    runs-on: ubuntu-latest
    needs: buildeo
    if: ${{ success() }}
    steps:
      - run: echo "Los test han corrido exitosamente!"

  pusheo:
    runs-on: ubuntu-latest
    needs: testeo
    if: ${{ success() }}
    steps:
      - run: echo "Build pusheada correctamente!"