name: Reusable Workflow

on:
  workflow_call:
    inputs:
      image-to-build:
        required: true
        type: string
    secrets:
      dhuser:
        required: true
      dhpass:
        required: true
permissions: write-all 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all 

    steps:
      - uses: actions/checkout@v4

      - name: Output the input value
        run: |
          echo "The node version to use is: ${{ inputs.image-to-build }}"

      - name: Checkout
        uses: actions/checkout@v4
      # Add your test steps here if needed...
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image-to-build }}
          tags: type=sha
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dhuser }}
          password: ${{ secrets.dhpass }}
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dboffelli/ngnixtest:latest
